import { Inject, Logger } from '@nestjs/common'
import { Processor, WorkerHost } from '@nestjs/bullmq'
import type { Job } from 'bullmq'
import { StorageService } from '@/modules/storage/storage.service'
import { DECK_CONCURRENCY, DECK_QUEUE, PPTX_MIME } from './decks.constants'
import { DECK_GENERATOR, type DeckGenerator } from './deck-generator.port'
import { DecksService } from './decks.service'

export interface DeckJobData {
  deckId: string
}

/**
 * Local concurrency matches the global cap. The global limit is what actually bounds spend
 * (see decks.module.ts); this only stops a single worker from exceeding it on its own.
 */
@Processor(DECK_QUEUE, { concurrency: DECK_CONCURRENCY })
export class DecksProcessor extends WorkerHost {
  private readonly logger = new Logger(DecksProcessor.name)

  constructor(
    private readonly decks: DecksService,
    private readonly storage: StorageService,
    @Inject(DECK_GENERATOR) private readonly generator: DeckGenerator,
  ) {
    super()
  }

  async process(job: Job<DeckJobData>): Promise<void> {
    const { deckId } = job.data
    const deck = await this.decks.findForJob(deckId)
    if (!deck) {
      // The row was deleted while queued. Nothing to write results to, so drop the job
      // rather than retrying into a permanent failure.
      this.logger.warn(`Deck ${deckId} vanished before generation; dropping job ${job.id}`)
      return
    }

    await this.decks.markGenerating(deckId)

    try {
      const generated = await this.generator.generate({
        prompt: deck.prompt,
        slideCount: deck.slideCount,
        language: deck.language,
        template: deck.template,
      })

      // Same bucket and credentials as every other file, under a decks/ prefix. The key is
      // generated by StorageService, never taken from the generator's filename — that name is
      // model-authored, can run to ~100 characters, and has been seen to contain an invented
      // presenter name and date.
      const { key } = await this.storage.uploadBuffer(
        'decks',
        generated.buffer,
        generated.mimeType || PPTX_MIME,
        'document',
      )

      await this.decks.markReady(
        deckId,
        key,
        generated.buffer.byteLength,
        this.titleFor(deck.prompt),
      )
      this.logger.log(`Deck ${deckId} ready at ${key} (${generated.buffer.byteLength} bytes)`)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      await this.decks.markFailed(deckId, message)
      this.logger.error(`Deck ${deckId} failed: ${message}`)
      throw err
    }
  }

  /**
   * Title comes from the student's own prompt, not the generator's filename. Predictable,
   * and it never surfaces details the model invented.
   */
  private titleFor(prompt: string): string {
    const firstLine = prompt.trim().split('\n')[0].trim()
    return firstLine.length > 120 ? `${firstLine.slice(0, 117)}...` : firstLine
  }
}
