import { Inject, Logger } from '@nestjs/common'
import { Processor, WorkerHost } from '@nestjs/bullmq'
import type { Job } from 'bullmq'
import { StorageService } from '@/modules/storage/storage.service'
import { DECK_CONCURRENCY, DECK_QUEUE, PPTX_MIME, REEXPORT_JOB } from './decks.constants'
import {
  DECK_EDITOR,
  DECK_GENERATOR,
  type DeckEditor,
  type DeckExport,
  type DeckGenerator,
} from './deck-generator.port'
import { DecksService } from './decks.service'

export interface DeckJobData {
  deckId: string
}

/**
 * Local concurrency matches the global cap. The global limit is what actually bounds spend
 * (see decks.module.ts); this only stops a single worker from exceeding it on its own.
 */
@Processor(DECK_QUEUE, { concurrency: DECK_CONCURRENCY })
export class DecksProcessor extends WorkerHost {
  private readonly logger = new Logger(DecksProcessor.name)

  constructor(
    private readonly decks: DecksService,
    private readonly storage: StorageService,
    @Inject(DECK_GENERATOR) private readonly generator: DeckGenerator,
    @Inject(DECK_EDITOR) private readonly editor: DeckEditor,
  ) {
    super()
  }

  async process(job: Job<DeckJobData>): Promise<void> {
    if (job.name === REEXPORT_JOB) return this.reexport(job.data.deckId)
    return this.generate(job)
  }

  private async generate(job: Job<DeckJobData>): Promise<void> {
    const { deckId } = job.data
    const deck = await this.decks.findForJob(deckId)
    if (!deck) {
      // The row was deleted while queued. Nothing to write results to, so drop the job
      // rather than retrying into a permanent failure.
      this.logger.warn(`Deck ${deckId} vanished before generation; dropping job ${job.id}`)
      return
    }

    const attempt = job.attemptsMade + 1
    await this.decks.markGenerating(deckId, attempt)

    try {
      const generated = await this.generator.generate({
        prompt: deck.prompt,
        slideCount: deck.slideCount,
        language: deck.language,
        template: deck.template,
        tone: deck.tone,
        verbosity: deck.verbosity,
        instructions: deck.instructions,
        includeTitleSlide: deck.includeTitleSlide,
        includeTableOfContents: deck.includeTableOfContents,
        webSearch: deck.webSearch,
      })

      const key = await this.store(generated.pptx)
      const pdfKey = generated.pdf ? await this.store(generated.pdf) : null

      await this.decks.markReady(deckId, {
        key,
        pdfKey,
        sizeBytes: generated.pptx.buffer.byteLength,
        title: this.titleFor(deck.prompt),
        externalId: generated.externalId,
      })
      this.logger.log(`Deck ${deckId} ready at ${key}${pdfKey ? ' (+pdf)' : ''}`)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      const maxAttempts = job.opts.attempts ?? 1

      // Only the LAST attempt marks the deck failed. Marking it on every attempt made a deck
      // that BullMQ was still retrying look permanently dead, which is how a transient
      // provider error turned into a wasted quota slot.
      if (attempt >= maxAttempts) {
        await this.decks.markFailed(deckId, message)
        this.logger.error(`Deck ${deckId} failed after ${attempt} attempts: ${message}`)
      } else {
        await this.decks.markRetrying(deckId, attempt, message)
        this.logger.warn(
          `Deck ${deckId} attempt ${attempt}/${maxAttempts} failed, will retry: ${message}`,
        )
      }
      throw err
    }
  }

  /**
   * Re-render an already-generated deck so the stored files catch up with edited slides.
   * No model call, so this is seconds rather than minutes.
   */
  private async reexport(deckId: string): Promise<void> {
    const deck = await this.decks.findForJob(deckId)
    if (!deck?.externalId) {
      this.logger.warn(`Deck ${deckId} has no external id; dropping re-export`)
      return
    }

    try {
      const { pptx, pdf } = await this.editor.reexport(deck.externalId)
      await this.decks.markReexported(deckId, {
        key: await this.store(pptx),
        pdfKey: pdf ? await this.store(pdf) : null,
        sizeBytes: pptx.buffer.byteLength,
      })
      this.logger.log(`Deck ${deckId} re-exported`)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      await this.decks.markFailed(deckId, message)
      this.logger.error(`Deck ${deckId} re-export failed: ${message}`)
      throw err
    }
  }

  /**
   * Same bucket and credentials as every other file, under a decks/ prefix. The key is
   * generated by StorageService, never taken from the generator's filename — that name is
   * model-authored, can run to ~100 characters, and has been seen to contain an invented
   * presenter name and date.
   *
   * Old objects are deliberately NOT deleted on re-export: a presigned URL handed out a
   * minute ago should keep working until it expires.
   */
  private store(file: DeckExport): Promise<string> {
    return this.storage
      .uploadBuffer('decks', file.buffer, file.mimeType || PPTX_MIME, 'document')
      .then((r) => r.key)
  }

  /**
   * Title comes from the student's own prompt, not the generator's filename. Predictable,
   * and it never surfaces details the model invented.
   */
  private titleFor(prompt: string): string {
    const firstLine = prompt.trim().split('\n')[0].trim()
    return firstLine.length > 120 ? `${firstLine.slice(0, 117)}...` : firstLine
  }
}
