import { Inject, Injectable, Logger } from '@nestjs/common'
import { StorageService } from '@/modules/storage/storage.service'
import { PPTX_MIME } from './decks.constants'
import { DECK_EDITOR, type DeckEditor, type DeckExport } from './deck-generator.port'

/**
 * Storing and unstoring a deck's rendered files.
 *
 * Shared by the two processors — generation and re-rendering — which both upload the same pair
 * of files and both have to clean them up when the deck they belong to turns out to have been
 * deleted mid-flight. Extracted rather than duplicated because the cleanup half is the easy
 * thing to get subtly wrong twice.
 */
@Injectable()
export class DeckArtifactsService {
  private readonly logger = new Logger(DeckArtifactsService.name)

  constructor(
    private readonly storage: StorageService,
    @Inject(DECK_EDITOR) private readonly editor: DeckEditor,
  ) {}

  /**
   * Same bucket and credentials as every other file, under a decks/ prefix. The key is
   * generated by StorageService, never taken from the generator's filename — that name is
   * model-authored, can run to ~100 characters, and has been seen to contain an invented
   * presenter name and date.
   *
   * Old objects are deliberately NOT deleted on re-render: a presigned URL handed out a
   * minute ago should keep working until it expires.
   */
  store(file: DeckExport): Promise<string> {
    return this.storage
      .uploadBuffer('decks', file.buffer, file.mimeType || PPTX_MIME, 'document')
      .then((r) => r.key)
  }

  /**
   * Files produced for a deck that was deleted before they could be recorded.
   *
   * Best-effort and never rethrown: the job did its work and the deck is gone either way, so
   * failing here would only retry work whose result is already unwanted.
   */
  async discardOrphans(
    deckId: string,
    keys: (string | null)[],
    externalId: string,
    ownerId: string,
  ): Promise<void> {
    this.logger.warn(`Deck ${deckId} was deleted mid-flight; discarding its output`)
    await Promise.all(
      keys
        .filter((k): k is string => Boolean(k))
        .map((key) =>
          this.storage
            .deleteFile(key)
            .catch((err) => this.logger.warn(`Orphaned object ${key}: ${String(err)}`)),
        ),
    )
    await this.editor.deletePresentation(externalId, ownerId)
  }
}
