import { Inject, Injectable, Logger } from '@nestjs/common'
import { StorageService } from '@/modules/storage/storage.service'
import { PPTX_MIME } from './decks.constants'
import { DECK_EDITOR, type DeckEditor, type DeckExport } from './deck-generator.port'

/**
 * Storing and unstoring a deck's rendered files.
 *
 * Shared by the two processors — generation and re-rendering — which both upload the same pair
 * of files and both have to clean them up when the deck they belong to turns out to have been
 * deleted mid-flight. Extracted rather than duplicated because the cleanup half is the easy
 * thing to get subtly wrong twice.
 */
@Injectable()
export class DeckArtifactsService {
  private readonly logger = new Logger(DeckArtifactsService.name)

  constructor(
    private readonly storage: StorageService,
    @Inject(DECK_EDITOR) private readonly editor: DeckEditor,
  ) {}

  /**
   * Same bucket and credentials as every other file, under a decks/ prefix. The key is
   * generated by StorageService, never taken from the generator's filename — that name is
   * model-authored, can run to ~100 characters, and has been seen to contain an invented
   * presenter name and date.
   *
   * Old objects are deliberately NOT deleted on re-render: a presigned URL handed out a
   * minute ago should keep working until it expires.
   */
  store(file: DeckExport): Promise<string> {
    return this.storage
      .uploadBuffer('decks', file.buffer, file.mimeType || PPTX_MIME, 'document')
      .then((r) => r.key)
  }

  /**
   * Deletes output that nothing is going to reference.
   *
   * Called for two different reasons, which is why `externalId` is nullable:
   *
   * - The deck was deleted mid-flight. Its generator presentation should go too, so pass the
   *   id.
   * - A job failed after uploading but before recording. The objects are unreferenced — the
   *   deck row still points at whatever it pointed at before — so they must be removed here,
   *   because this is the only place that still knows their keys. A failed RE-RENDER passes
   *   null: the deck still exists and its externalId has to keep working. A failed generation
   *   attempt passes the id, since the retry produces a fresh presentation and this one would
   *   otherwise sit on the generator forever.
   *
   * Best-effort and never rethrown. The caller is either finished with the deck or already
   * rethrowing its own failure; turning a cleanup error into the reported one would hide why
   * the job actually failed.
   */
  async discard(
    deckId: string,
    keys: (string | null)[],
    externalId: string | null,
    ownerId: string,
    reason: string,
  ): Promise<void> {
    const present = keys.filter((k): k is string => Boolean(k))
    if (present.length === 0 && !externalId) return

    this.logger.warn(`Deck ${deckId} ${reason}; discarding ${present.length} object(s)`)
    await Promise.all(
      present.map((key) =>
        this.storage
          .deleteFile(key)
          .catch((err) => this.logger.warn(`Orphaned object ${key}: ${String(err)}`)),
      ),
    )
    // Contractually never throws — see DeckEditor.deletePresentation.
    if (externalId) await this.editor.deletePresentation(externalId, ownerId)
  }
}
